export type VericadorResultado = "CONCORDANTE" | "DISCREPANCIA" | "DATO_INCOMPLETO";

export interface VerificationResult {
  resultado: VericadorResultado;
  duracionContrato: number | null; // Extracted from PDF
  plazoEntrega: number | null; // Extracted from PDF
  plazoPliego: number; // Always 10
  campoFaltante: string | null; // e.g. "Duración del contrato" or "Plazo de entrega" or "Ambos"
  detalleDiscrepancia: string | null; // Explanation of which value deviates
  explicacionIa: string | null; // Generated by Gemini
}
